[general]
import = ["~/.cache/wal/colors-alacritty.toml"]
# import = ["~/.config/alacritty/themes/aura-dark.toml"]

[cursor.style]
shape = "Block"
blinking = "On"

[env]
TERM = "xterm-256color"

[mouse]
hide_when_typing = true

[font]
# Set the point size
size = 12

[font.normal]
family = "CaskaydiaCove Nerd Font Mono"
style = "Regular"

## [font.italic]
# family = "ComicShannsMono Nerd Font"
# style = "Italic"

[font.bold]
family = "ComicShannsMono Nerd Font Propo"
style = "Bold"

## [font.bold_italic]
# family = "ComicShannsMono Nerd Font"
# style = "Bold Italic"

[font.glyph_offset]
x = 0
y = 0

[font.offset]
x = 0
y = 0

[scrolling]
history = 1000
multiplier = 3

[window]
dynamic_padding = true
decorations = "Full"
opacity = 1.0
startup_mode = "Windowed"
dynamic_title = true

[window.padding]
x = 35
y = 25

[selection]
semantic_escape_chars = ",â”‚`|:\"' ()[]{}<>\t"
save_to_clipboard = true

# [terminal.shell]
# program = "/bin/zsh"
# args = ["--login", "-c", "salut"]
