## Importing colorscheme is disabled. pywal is responsible for syncing colors with the wallpaper.
# [general]
# import = ["~/.config/alacritty/themes/aura-dark.toml"]

[cursor.style]
shape = "Block"
blinking = "On"

[env]
TERM = "xterm-256color"

[font]
# Set the point size
size = 10

[font.normal]
family = "ComicShannsMono Nerd Font Propo"
style = "Regular"

## [font.italic]
# family = "ComicShannsMono Nerd Font"
# style = "Italic"

[font.bold]
family = "ComicShannsMono Nerd Font Propo"
style = "Bold"

## [font.bold_italic]
# family = "ComicShannsMono Nerd Font"
# style = "Bold Italic"

[font.glyph_offset]
x = 0
y = 0

[font.offset]
x = 0
y = 0

[scrolling]
history = 1000
multiplier = 3

[window]
dynamic_padding = true
decorations = "Full"
opacity = 1.0
startup_mode = "Windowed"
dynamic_title = true

[window.padding]
x = 25
y = 25

[bell]
animation = "Linear"
duration = 500
color = "#c0caf5"

[selection]
semantic_escape_chars = ",â”‚`|:\"' ()[]{}<>\t"
save_to_clipboard = true

[terminal.shell]
program = "/bin/zsh"
args = ["--login", "-c", "salut"]
